name: Commandspy
main: moe.evelyn.albatross.Main
version: 5.0.2
author: Subarrow
description: Spy on your players. In style.
commands:
    commandspy:
      description: Access commandspy subcommands
      usage: /commandspy help
      aliases: [c, cs, cspy]
permissions:
    commandspy.configure:
        description: Allows use of configuration commands
        default: false
    commandspy.use:
        description: Allows user to define their own filters
        default: op
        children:
            commandspy.receive: true
    commandspy.receive:
        description: Allows general Commandspy filters to take effect
        default: op
    commandspy.set:
        description:
        default: false
        children:
            commandspy.use: true
    commandspy.on:
        description:
        default: false
        children:
          commandspy.use: true
